name: build-builder-multiarch

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build-arm64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: false
          tags: |
            riderlty/fontinass-builder-arm64:latest
  
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build-amd64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: false
          tags: |
            riderlty/fontinass-builder-amd64:latest

  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-arm64
      - build-amd64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
            inputs: riderlty/fontinass-builder:latest
            images: |
              riderlty/fontinass-builder-amd64:latest
              riderlty/fontinass-builder-arm64:latest
            push: true