name: build-builder-multiarch
on:
  workflow_dispatch:
jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build-arm64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: false
          provenance: false
          tags: |
            build-img-arm64
      
      - name: save img to artifacts 
        run: |
          docker save build-img-arm64 -o build-img-arm64.tar  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-img-arm64  # Artifact 名称
          path: build-img-arm64.tar


  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build-amd64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: false
          provenance: false
          tags: |
            build-img-amd64

      - name: save img to artifacts 
        run: |
          docker save build-img-amd64 -o build-img-amd64.tar  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-img-amd64  # Artifact 名称
          path: build-img-amd64.tar

  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-arm64
      - build-amd64
    steps:

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: build-img-arm64  # 下载名为 build-artifact 的 Artifact
          path: ./ 

      - name: Download amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: build-img-amd64  # 下载名为 build-artifact 的 Artifact
          path: ./ 

      - name: Load image
        run: |
          docker load -i build-img-arm64.tar
          docker load -i build-img-amd64.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
            inputs: riderlty/fontinass-builder:latest
            images: build-img-amd64,build-img-arm64
            push: true

      - name: clear
      - uses: geekyeggo/delete-artifact@v5
        with:
            name: |
                build-img-amd64
                build-img-arm64