name: test

on:
  workflow_dispatch:

jobs:
  build-on-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Calculate file hash
        id: calculate_hash
        run: |
          HASH=$(cat requirements.txt src/py2cy/c_utils.pyx src/py2cy/setup.py src/py2cy/cpp_utils.cpp | sha256sum  | awk '{ print $1 }')
          echo "FILE_HASH=$HASH" >> $GITHUB_ENV
      
      - name: Build and push default
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          platforms: |
            linux/arm64
          push: true
          tags: |
            riderlty/fontinass-builder:arm-test
